<?php
session_start();
// Auth check - only students can save answers
if (!isset($_SESSION["loggedin"]) || $_SESSION["loggedin"] !== true || $_SESSION["role"] !== 'student') {
    header("location: ../login.php");
    exit;
}

require_once '../src/Database.php';
require_once '../src/Exercise.php';

if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST['exercise_id'])) {
    $exerciseId = (int)$_POST['exercise_id'];
    $userId = $_SESSION['id'];

    // The structure of the answer depends on the form generated by the parser.
    // We'll collect all POST data except the exercise_id into an 'answers' array.
    $answerData = $_POST;
    unset($answerData['exercise_id']);

    // Get the database connection
    $db = Database::getInstance()->getConnection();
    $exercise_manager = new Exercise($db);
    $result = $exercise_manager->saveStudentAnswer($userId, $exerciseId, $answerData);

    if ($result === true) {
        $_SESSION['feedback'] = ['type' => 'success', 'message' => 'La tua risposta è stata salvata con successo.'];
    } else {
        $_SESSION['feedback'] = ['type' => 'danger', 'message' => 'Errore nel salvataggio della risposta: ' . htmlspecialchars($result)];
    }

    // Redirect back to the exercise view page
    header("location: view.php?id=" . $exerciseId);
    exit;

} else {
    // Redirect to dashboard if the request is not valid
    header("location: ../dashboard.php");
    exit;
}
?>
